linters-settings:
  govet:
    check-shadowing: false
  gocycle:
    min-complexity: 30
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - goimports
    - errcheck
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace
